name: Flutter CI/CD with CodeQL & Semgrep

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter-analyze-build:
    name: 🧱 Flutter Analyze & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5' # Compatible with Dart 3.8.1

      - name: Verify Flutter setup
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub --coverage

      - name: Build APK (optional)
        run: flutter build apk --release

  semgrep-scan:
    name: 🕵️ Semgrep Security Scan
    runs-on: ubuntu-latest
    needs: flutter-analyze-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (for Semgrep)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan
        run: semgrep --config p/ci --sarif --output semgrep-results/semgrep.sarif || true

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-results/semgrep.sarif
